# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CCTVMapper
                                 A QGIS plugin
 The plugin plots points along lines using a CSV file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-20
        copyright            : (C) 2019 by Ed B
        email                : boesiii@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CCTVMapper class from file CCTVMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cctv_mapper import CCTVMapper
    return CCTVMapper(iface)
